accounts/urls.py
from django.conf.urls import url
from .import views
from django.conf import settings
from django.contrib.auth.views import (
	login , logout , password_reset , password_reset_done, password_reset_confirm, password_reset_complete
	)
urlpatterns = [
	url(r'^$',views.home , name='home'),
	url(r'^login/$',login,{'template_name':'accounts/login.html'}, name='login'),
	url(r'^logout/$',logout,{'template_name':'accounts/logout.html'}, name='logout'),
	url(r'^register/$',views.register, name='register'),
	url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
	url(r'^profile/edit/$',views.edit_profile ,name='edit_profile'),
	url(r'^change-password/$',views.change_password, name='change_password'),
	url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),
 
    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),


    url(r'^reset-password/complete/$', password_reset_complete, name='password_reset_complete')
]     

 

health/urls.py
from django.conf.urls import url , include
from django.contrib import admin  
from health import views


urlpatterns = [
	url(r'^$',views.login_redirect , name='login_redirect'),
	url(r'^admin/',admin.site.urls),
	url(r'^account/', include('accounts.urls',namespace='accounts')),
    url(r'^diseases/',include('disease.urls')),
]
   

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfile(models.Model):
	user = models.OneToOneField(User)
	description = models.CharField(max_length=100, default='')
	city = models.CharField(max_length=100, default='')
	phone =models.IntegerField(default=0)
 
def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile= UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']


        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',
            
        )

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render , redirect
from accounts.forms import RegistrationForm , EditProfileForm 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm ,PasswordChangeForm 
from django.contrib.auth import update_session_auth_hash 
from django.contrib.auth.decorators import login_required

# Create your views here.
def home(request):
	return render(request,'accounts/login.html')
def register(request):
	if request.method =='POST':
		form=RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/account/')
		else:
			form=RegistrationForm(request.POST)

	else:
		form =RegistrationForm()

		args = {'form': form}
		return render(request,'accounts/reg_form.html',args)  

def profile(request):
	args= {'user':request.user}
	return render(request,'accounts/profile.html',args)

def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
	if request.method == 'POST':
		form= EditProfileForm(request.POST,  instance=request.user)

		if form.is_valid():
			form.save()
			return redirect('/account/profile')
	else:
		form=EditProfileForm(instance=request.user)
		args={'form':form}
		return render(request,'accounts/edit_profile.html',args)

def change_password(request):
	if request.method=='POST':
		form=PasswordChangeForm(data=request.POST, user=request.user)
		if form.is_valid():
			form.save()
			update_session_auth_hash(request,form.user)
			return redirect('/account/profile')
		else:
			return redirect('/account/change-password')
	else:
		form=PasswordChangeForm(user=request.user)
		args={'form':form}
		return render(request,'accounts/change_password.html',args)

accounts/templates/accounts/change_password.html
<head>
<style type="text/css">
	
	#d1 {
         text-align: left;
         width: 600px;
         padding-left: 14px;
         margin-top: 20px;
         margin-left: 370px;
         background-color: #f2f2f2;
         border-top-style: outset;
        border-left-style: outset;
        border-bottom-style: inset;
        border-right-style: inset;
        border-radius: 8px;
 
    }

    #d2 {
    	align-items: center;
    }

    #btn1 {
    	position: relative;
    	left: 31%;
    	width: 200px;
    }

</style>
{% extends 'base.html' %}

<body>
{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}

<div class="container" id="d1">
<h1 style="font-family: TimesNewRoman; font-size: 45px; text-align: center;"><strong>Change Password</strong></h1>
<br>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        
        <button class="btn btn-primary btn-lg" type="submit" style="align-self: center;" id="btn1">Submit</button>
        
        <br>
    </form>
    <br>
</div>

{% endblock %}
</body>
</head>

accounts/templates/accounts/edit_profile.html
<head>
<style type="text/css">
	
	#d1 {

		 text-align: center;
         width: 600px;
         padding-left: 14px;
         margin-top: 80px;
         margin-left: 370px;
         background-color: #f2f2f2;
         border-top-style: outset;
        border-left-style: outset;
        border-bottom-style: inset;
        border-right-style: inset;
        border-radius: 8px;
	}

	#btn1 {
		font-family: Georgia;
		text-align: center; 
        display: inline-block;
        width: 200px;
        position: relative;
        left: 33%;
	}

</style>

{% extends 'base.html' %}

{% block head %}
<title>Profile</title>

{% endblock %}

<body>
{% block body %}

<div class="container" id="d1">
	<br>
	<h1 style="font-family: TimesNewRoman;"><strong>Edit your Profile : </strong></h1>
	<br>
	<br>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <br>
    <br>
        <button class="btn btn-primary btn-lg" type="submit" id="btn1">Submit</button>
    <br>
    <br>
    </form>
    <br>
</div>

{% endblock %}
</body>
</head>

accounts/templates/accounts/login.html
<head>
    <style >
    /*#d2
    {
        border-top-style: outset;
        border-left-style: outset;
        border-bottom-style: outset;
        border-right-style: outset;
        border-radius: 5px;
    
        display: block;
        margin-left: auto;
        margin-right: auto;
        position: relative;
        padding: 
        width: 50%;
        height:50%;
    
        font-size: 110%;
    }*/

    #d1 {
        /*background-color: #e2edff;*/
        /*background: radial-gradient(circle,#e2edff,#166eff,#5e96f2,#d6e5ff);*/
        /*background: radial-gradient(circle,#f9f7f7,#e5dcdc,#b7b5b5);*/
        /* background:url('img_div.png') no-repeat center top;*/
        background-color: #ffc600;
        width: 400px;
        /*border: 3px solid black;*/
        padding: 25px;
        margin: -50px;
        background-color: #f2f2f2;
        border-top-style: outset; 
        border-left-style: outset;
        border-bottom-style: inset;
        border-right-style: inset;
        border-width: 2px;
        border-radius: 8px;
        font-size: 110%;
        position: relative;
        left: 440px;

    }

    /*#h1 {
        text-decoration: underline;
        -webkit-text-decoration-style: wavy; 
        -webkit-text-decoration-color: #828282; 
        text-shadow: 1px 2px grey;

    }*/

    #btn1 {
       font-family: Georgia;
        text-align: center; 
        display: inline-block;
        width: 200px;
        position: relative;
        
    }

    

</style>
{% extends 'base.html' %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>


<body>
{% block body %}
<div class="container" style="text-align:center; margin-top: 80px; margin-left: -120px;" id="d2">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8 container">
    <div class="container" id="d1">

        
        
        <h2 style="font-style: bold; font-family: Times New Roman, serif;; font-size: 325%; text-shadow: 1px 2px grey; ">Login</h2>
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <p style="font-family: verdana">
            <i>Please enter your appropriate username and password.</i>
            </p>
            <br>
            <button class="btn btn-primary btn-lg " id="btn1"  type="submit">Login</button>
            <br>
            <br>
            

        </form>
    </div>
    <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

</body>
</head>

accounts/templates/accounts/logout.html
<head>

<style type="text/css">
	
	 #d1 {
         text-align: center;
         width: 600px;
         padding-left: 14px;
         margin-top: 80px;
         margin-left: 370px;
         background-color: #f2f2f2;
         border-top-style: outset;
        border-left-style: outset;
        border-bottom-style: inset;
        border-right-style: inset;
        border-radius: 8px;
 
    }

</style>

{% extends 'base.html' %}
<body>

{% block body %}
<div class="container" id="d1">
    <h1 style="font-family: Times New Roman; font-size: 350%; text-align-last: center;">Logged out</h1>
    <br>
    <p>
    	You have successfully logged out of your account.
    </p>
    <br>
  
    <p><i>Please visit us again.</i></p>

  </div>
{% endblock %}  
</body>
</head>

accounts/templates/accounts/profile.html
<head>

<style type="text/css">
    
    #d1 {
         text-align: center;
         width: 600px;
         padding-left: 14px;
         margin-top: 80px;
         margin-left: 370px;
         background-color: #f2f2f2;
         border-top-style: outset;
        border-left-style: outset;
        border-bottom-style: inset;
        border-right-style: inset;
        border-radius: 8px;
 
    }

    #d2 {

        text-align: left; 
        font-family: Verdana;
        font-size: 14px;
    }

    #h1 {
        font-family: Times New Roman;
        font-size: 200%;
        font-style: bold;

    }

</style>

{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

<body>
{% block body %}
<div class="container" id="d1">
    <h1 style="font-family: Times New Roman; font-size: 45px;"><strong>Profile</strong></h1>
    <br>
    <br>
    <div class="container" id="d2">
    <p><strong>Username:</strong> {{ user }}</p>
    <p><strong>First name:</strong> {{ user.first_name }}</p>
    <p><strong>Last name:</strong> {{ user.last_name }}</p>
    <p><strong>Email:</strong> {{ user.email }}</p>
    <p><strong>Description:</strong> {{ user.userprofile.description }}</p>
    <p><strong>Phone:</strong> {{ user.userprofile.phone }}</p>
    <p><strong>City:</strong> {{ user.userprofile.city }}</p>
    <p><strong>Website:</strong> {{ user.userprofile.website }}</p>
    <br>
    <br>
    {% if user.userprofile.image %}
    <img src="{{ user.userprofile.image.url }}" width="240">

    </div>
    {% endif %}
</div>

{% endblock %}
</body>
</head>

accounts/templates/accounts/reg_form.html
<head>
	<style type="text/css">
		
	#body {

	     margin: 0;
	     padding: 0;
	     background: #eff0f2;
	     text-align: center;

   		 }

   	#h1 {

   		font-size: 200%;
   		font-family: Times New Roman;
   		font-style: bold;
   	}


	#d2 {
	     
	     text-align: left;
         width: 600px;
         padding-left: 14px;
         margin-top: 20px;
         margin-left: 370px;
         background-color: #f2f2f2;
         border-top-style: outset;
        border-left-style: outset;
        border-bottom-style: inset;
        border-right-style: inset;
        border-radius: 8px;

		}

	#btn1 {
		font-family: Georgia;
		text-align: center; 
        display: inline-block;
        width: 200px;
        position: relative;
        left: 33%;
	}

	</style>
{% extends 'base.html' %}

<body>
{% block body %}
<div class="container" id="d2">
	<h1 style="font-family: Times New Roman; font-size: 350%; text-align-last: center;">Registration<br></h1>
	<br>
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<br>
		<p style="font-family: Georgia;"><strong> <i>Please enter accurate details.</i></strong></p>
		<br>
		<button class="btn btn-primary btn-lg" type="submit" id="btn1">Submit</button>
	</form>
</div>

{% endblock %} 
</body>
</head>

accounts/templates/accounts/reset_password.html
<head>
	<style type="text/css">
	
     #d1 {
         text-align: center;
         width: 600px;
         padding-left: 14px;
         margin-top: 80px;
         margin-left: 370px;
         background-color: #f2f2f2;
         border-top-style: outset;
        border-left-style: outset;
        border-bottom-style: inset;
        border-right-style: inset;
        border-radius: 8px;
 
    } 


	</style>

	
{% extends 'base.html' %}

{% block body %}
<div class="container" id="d1">
    <h1 style="font-family: TimeNewRoman; font-size: 45px;"><strong>Password reset</strong></h1>
    <br>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <br>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button class="btn btn-primary btn-lg" type="submit">Reset password</button>
        <br>
        <br>
    </form>
</div>
{% endblock %}
</head>

accounts/templates/accounts/reset_password_complete.html
<head>
<style type="text/css">
	
	#d1 {
         text-align: center;
         width: 600px;
         padding-left: 14px;
         margin-top: 80px;
         margin-left: 370px;
         background-color: #f2f2f2;
         border-top-style: outset;
        border-left-style: outset;
        border-bottom-style: inset;
        border-right-style: inset;
        border-radius: 8px;
 
    }

</style>

{% extends 'base.html' %}


<body>
{% block body %}
<div class="container" id="d1">#d1 {
         text-align: center;
         width: 600px;
         padding-left: 14px;
         margin-top: 80px;
         margin-left: 370px;
         background-color: #f2f2f2;
         border-top-style: outset;
        border-left-style: outset;
        border-bottom-style: inset;
        border-right-style: inset;
        border-radius: 8px;
 
    }
    <h1><strong>Your Passwor has been successfully reset.</strong></h1>
    <br>
    <a href="{% url 'accounts:login' %}">Log in</a>
    <br>
</div>
{% endblock %}
</body>
</head>

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Enter new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
<head>
<style type="text/css">
	
	#d1 {
         text-align: center;
         width: 600px;
         padding-left: 14px;
         margin-top: 80px;
         margin-left: 370px;
         background-color: #f2f2f2;
         border-top-style: outset;
        border-left-style: outset;
        border-bottom-style: inset;
        border-right-style: inset;
        border-radius: 8px;
 
    }

</style>
{% extends 'base.html' %}

<body>
{% block body %}
<div class="container" id="d1">
    <h1 style="font-family: TimesNewRoman; font-size: 45px;"><strong>Your Password has been successfully reset.</strong></h1>
    <br>
    
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock %}
</body>
</head>

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}