accounts/urls.py
from django.conf.urls import url
from .import views
from django.conf import settings
from django.contrib.auth.views import (
	login , logout , password_reset , password_reset_done, password_reset_confirm, password_reset_complete
	)
urlpatterns = [
	url(r'^$',views.home , name='home'),
	url(r'^login/$',login,{'template_name':'accounts/login.html'}, name='login'),
	url(r'^logout/$',logout,{'template_name':'accounts/logout.html'}, name='logout'),
	url(r'^register/$',views.register, name='register'),
	url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
	url(r'^profile/edit/$',views.edit_profile ,name='edit_profile'),
	url(r'^change-password/$',views.change_password, name='change_password'),
	url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),
 
    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),


    url(r'^reset-password/complete/$', password_reset_complete, name='password_reset_complete')
]     

 

health/urls.py
from django.conf.urls import url , include
from django.contrib import admin  
from health import views


urlpatterns = [
	url(r'^$',views.login_redirect , name='login_redirect'),
	url(r'^admin/',admin.site.urls),
	url(r'^account/', include('accounts.urls',namespace='accounts')),
    url(r'^diseases/',include('disease.urls')),
]
   

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfile(models.Model):
	user = models.OneToOneField(User)
	description = models.CharField(max_length=100, default='')
	city = models.CharField(max_length=100, default='')
	phone =models.IntegerField(default=0)
 
def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile= UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']


        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',
            
        )

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render , redirect
from accounts.forms import RegistrationForm , EditProfileForm 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm ,PasswordChangeForm 
from django.contrib.auth import update_session_auth_hash 
from django.contrib.auth.decorators import login_required

# Create your views here.
def home(request):
	return render(request,'accounts/login.html')
def register(request):
	if request.method =='POST':
		form=RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/account/')
		else:
			form=RegistrationForm(request.POST)

	else:
		form =RegistrationForm()

		args = {'form': form}
		return render(request,'accounts/reg_form.html',args)  

def profile(request):
	args= {'user':request.user}
	return render(request,'accounts/profile.html',args)

def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
	if request.method == 'POST':
		form= EditProfileForm(request.POST,  instance=request.user)

		if form.is_valid():
			form.save()
			return redirect('/account/profile')
	else:
		form=EditProfileForm(instance=request.user)
		args={'form':form}
		return render(request,'accounts/edit_profile.html',args)

def change_password(request):
	if request.method=='POST':
		form=PasswordChangeForm(data=request.POST, user=request.user)
		if form.is_valid():
			form.save()
			update_session_auth_hash(request,form.user)
			return redirect('/account/profile')
		else:
			return redirect('/account/change-password')
	else:
		form=PasswordChangeForm(user=request.user)
		args={'form':form}
		return render(request,'accounts/change_password.html',args)

accounts/templates/base.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href='https://fonts.googleapis.com/css?family=Merriweather|Oswald:400,700,300' rel='stylesheet' type='text/css'>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block head %}
        <title>Base</title>
        {% endblock %}
        <style>
          body{
            background: url('{% static "images/img19.jpg" %}') no-repeat center center fixed;
            background-size: cover;
            -webkit-background-size: cover;
            -moz-background-size: cover;
          }
        </style>
    </head>
    <body>
        <br>
        <div class="container">
            <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/" style="font-family: TimesNewRoman;">CURIS</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                   <li><a href="{% url 'accounts:home' %}">Home</a>
                    <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                    <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
                  <li><a href="{% url 'accounts:register' %}">Register</a></li>
                </ul>
                {% endif %}
              </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
          </nav>
        </div>
        

<style type="text/css">

                body {

                                padding: 2em;

                                font-family: Merriweather;

                                background-color: #fe9;

                }

                h1,h2,h3 {

                                font-family: Oswald;

                }

                a {

                                padding: .5em;

                                border-radius: 4px;

                                background: #888;

                                color: #fff;

                                text-decoration: none;

                }

                ul {

                                list-style: none;

                                }

                .success {

                                background-color: #2f8;

                                padding: 1em;

                                width: 50%;

                }

                .warning {

                                background-color: #f62;

                                padding: 1em;

                                width: 50%;

                }

</style>

                
</head>

<body>

 

{% if messages %}

<div class="messages">

    {% for message in messages %}

    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>

    {% endfor %}

</div>

{% endif %}

 

{% block body %}

{% endblock body %}
       
    </body>
    
</html>